apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-09-21T17:26:04Z"
  labels:
    app: blogclient
  name: service-client
  namespace: default
  resourceVersion: "15218"
  uid: ac68d883-bbc5-4333-9c02-2e5c9fdb46b7
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.54.59
  clusterIPs:
  - 10.106.54.59
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31034
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: blogclient
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
